check

diff --git a/.github/workflows/ci-cd-pipeline.yml b/.github/workflows/ci-cd-pipeline.yml
--- a/.github/workflows/ci-cd-pipeline.yml
+++ b/.github/workflows/ci-cd-pipeline.yml
@@ -8,6 +8,7 @@ on:
     branches:
       - main
 
+
 jobs:
   build-and-deploy:
     runs-on: ubuntu-latest
@@ -76,20 +77,20 @@ jobs:
           cluster: ${{ secrets.ECS_CLUSTER }}
           wait-for-service-stability: true
 #
-#      # Step 9: Post-deployment Health Check
-#      - name: Health Check
-#        env:
-#          SERVICE_URL: ${{ secrets.SERVICE_URL }}
-#        run: |
-#          echo "Checking service health at $SERVICE_URL"
-#          for i in {1..10}; do
-#            STATUS=$(curl -s -o /dev/null -w '%{http_code}' $SERVICE_URL)
-#            if [ "$STATUS" -eq 200 ]; then
-#              echo "Service is healthy!"
-#              exit 0
-#            fi
-#            echo "Service not healthy. Retrying in 10 seconds..."
-#            sleep 10
-#          done
-#          echo "Service health check failed."
-#          exit 1
+      # Step 9: Post-deployment Health Check
+      - name: Health Check
+        env:
+          SERVICE_URL: ${{ secrets.SERVICE_URL }}
+        run: |
+          echo "Checking service health at $SERVICE_URL"
+          for i in {1..10}; do
+            STATUS=$(curl -s -o /dev/null -w '%{http_code}' $SERVICE_URL)
+            if [ "$STATUS" -eq 200 ]; then
+              echo "Service is healthy!"
+              exit 0
+            fi
+            echo "Service not healthy. Retrying in 10 seconds..."
+            sleep 10
+          done
+          echo "Service health check failed."
+          exit 1
