check4

diff --git a/.github/workflows/ci-cd-pipeline.yml b/.github/workflows/ci-cd-pipeline.yml
--- a/.github/workflows/ci-cd-pipeline.yml
+++ b/.github/workflows/ci-cd-pipeline.yml
@@ -29,8 +29,18 @@ jobs:
           DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
           JWT_SECRET: ${{ secrets.JWT_SECRET }}
         run: |
-          mvn clean install --no-transfer-progress || exit 1
-        continue-on-error: false
+          mvn clean install --no-transfer-progress || (
+            echo "Build or tests failed. Showing test reports:"
+            cat target/surefire-reports/*.txt || echo "No test reports found."
+            exit 1
+          )
+
+      - name: Upload Test Results
+        if: always() # Always upload test results, even if the step fails
+        uses: actions/upload-artifact@v3
+        with:
+          name: surefire-reports
+          path: target/surefire-reports/
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
@@ -39,13 +49,16 @@ jobs:
         uses: actions/cache@v2
         with:
           path: /tmp/.buildx-cache
-          key: ${{ runner.os }}-buildx-${{ github.sha }}
+          key: ${{ runner.os }}-docker-${{ github.sha }}
           restore-keys: |
-            ${{ runner.os }}-buildx-
+            ${{ runner.os }}-docker-
 
       - name: Build Docker image
         run: |
-          docker build -t abhishek94733/tiameds-labs:${{ github.sha }} .
+          docker build --cache-from=type=local,src=/tmp/.buildx-cache \
+            --cache-to=type=local,dest=/tmp/.buildx-cache \
+            -t abhishek94733/tiameds-labs:${{ github.sha }} \
+            -t abhishek94733/tiameds-labs:latest .
 
       - name: Log in to Docker Hub
         uses: docker/login-action@v2
@@ -56,3 +69,4 @@ jobs:
       - name: Push Docker image
         run: |
           docker push abhishek94733/tiameds-labs:${{ github.sha }}
+          docker push abhishek94733/tiameds-labs:latest
