check 32

diff --git a/.github/workflows/ci-cd-pipeline.yml b/.github/workflows/ci-cd-pipeline.yml
--- a/.github/workflows/ci-cd-pipeline.yml
+++ b/.github/workflows/ci-cd-pipeline.yml
@@ -51,8 +51,8 @@ jobs:
       - name: Build, Tag, and Push Docker Image to Amazon ECR
         env:
           ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
-          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
           IMAGE_TAG: ${{ github.sha }}
+          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
         run: |
           echo "Building Docker image $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
           docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
@@ -75,21 +75,21 @@ jobs:
           service: ${{ secrets.ECS_SERVICE }}
           cluster: ${{ secrets.ECS_CLUSTER }}
           wait-for-service-stability: true
-
-      # Step 9: Post-deployment Health Check
-      - name: Health Check
-        env:
-          SERVICE_URL: ${{ secrets.SERVICE_URL }}
-        run: |
-          echo "Checking service health at $SERVICE_URL"
-          for i in {1..10}; do
-            STATUS=$(curl -s -o /dev/null -w '%{http_code}' $SERVICE_URL)
-            if [ "$STATUS" -eq 200 ]; then
-              echo "Service is healthy!"
-              exit 0
-            fi
-            echo "Service not healthy. Retrying in 10 seconds..."
-            sleep 10
-          done
-          echo "Service health check failed."
-          exit 1
+#
+#      # Step 9: Post-deployment Health Check
+#      - name: Health Check
+#        env:
+#          SERVICE_URL: ${{ secrets.SERVICE_URL }}
+#        run: |
+#          echo "Checking service health at $SERVICE_URL"
+#          for i in {1..10}; do
+#            STATUS=$(curl -s -o /dev/null -w '%{http_code}' $SERVICE_URL)
+#            if [ "$STATUS" -eq 200 ]; then
+#              echo "Service is healthy!"
+#              exit 0
+#            fi
+#            echo "Service not healthy. Retrying in 10 seconds..."
+#            sleep 10
+#          done
+#          echo "Service health check failed."
+#          exit 1
